version: '3.1'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

volumes:
  mongodb_data:
  
#docker compose up
#docker exec -it 37eb82127b6a /bin/bash
#mongo -u root -p rootpassword
#docker volume create mongodb_data
#docker run -v mongodb_data:/data/db mongo:latest